package com.chan.model;

import com.chan.util.BaseModel;
import org.springframework.stereotype.Component;

import java.io.UnsupportedEncodingException;
import java.util.Date;

@Component
public class MsgFile extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.DCOUNT
     *
     * @mbggenerated
     */
    private Integer dcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.UPLOAD_DATE
     *
     * @mbggenerated
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.FILE_PATH
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.FILE_TYPE
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_file.MSG_ID
     *
     * @mbggenerated
     */
    private Integer msgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    public MsgFile(Integer id, String fileName, String note, Integer dcount, Date uploadDate, String filePath, String fileType, Integer msgId) {
        this.id = id;
        this.fileName = fileName;
        this.note = note;
        this.dcount = dcount;
        this.uploadDate = uploadDate;
        this.filePath = filePath;
        this.fileType = fileType;
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.ID
     *
     * @return the value of msg_file.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.FILE_NAME
     *
     * @return the value of msg_file.FILE_NAME
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.NOTE
     *
     * @return the value of msg_file.NOTE
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.DCOUNT
     *
     * @return the value of msg_file.DCOUNT
     * @mbggenerated
     */
    public Integer getDcount() {
        return dcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.UPLOAD_DATE
     *
     * @return the value of msg_file.UPLOAD_DATE
     * @mbggenerated
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.FILE_PATH
     *
     * @return the value of msg_file.FILE_PATH
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.FILE_TYPE
     *
     * @return the value of msg_file.FILE_TYPE
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_file.MSG_ID
     *
     * @return the value of msg_file.MSG_ID
     * @mbggenerated
     */
    public Integer getMsgId() {
        return msgId;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setFileName(String fileName) {
        try {
            this.fileName = new String(fileName.getBytes("iso-8859-1"), "utf-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }

    public void setNote(String note) {
        this.note = note;
    }

    public void setDcount(Integer dcount) {
        this.dcount = dcount;
    }

    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    public MsgFile() {
    }
}