package com.chan.model;

import java.util.ArrayList;
import java.util.List;

public class MsgTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public MsgTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("TYPE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("TYPE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("TYPE_NAME =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("TYPE_NAME <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("TYPE_NAME >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("TYPE_NAME <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("TYPE_NAME <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("TYPE_NAME like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("TYPE_NAME not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("TYPE_NAME in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("TYPE_NAME not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("TYPE_NAME between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("TYPE_NAME not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTMsgIdIsNull() {
            addCriterion("T_MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andTMsgIdIsNotNull() {
            addCriterion("T_MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTMsgIdEqualTo(String value) {
            addCriterion("T_MSG_ID =", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdNotEqualTo(String value) {
            addCriterion("T_MSG_ID <>", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdGreaterThan(String value) {
            addCriterion("T_MSG_ID >", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("T_MSG_ID >=", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdLessThan(String value) {
            addCriterion("T_MSG_ID <", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdLessThanOrEqualTo(String value) {
            addCriterion("T_MSG_ID <=", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdLike(String value) {
            addCriterion("T_MSG_ID like", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdNotLike(String value) {
            addCriterion("T_MSG_ID not like", value, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdIn(List<String> values) {
            addCriterion("T_MSG_ID in", values, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdNotIn(List<String> values) {
            addCriterion("T_MSG_ID not in", values, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdBetween(String value1, String value2) {
            addCriterion("T_MSG_ID between", value1, value2, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgIdNotBetween(String value1, String value2) {
            addCriterion("T_MSG_ID not between", value1, value2, "tMsgId");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleIsNull() {
            addCriterion("T_MSG_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleIsNotNull() {
            addCriterion("T_MSG_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleEqualTo(String value) {
            addCriterion("T_MSG_TITLE =", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleNotEqualTo(String value) {
            addCriterion("T_MSG_TITLE <>", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleGreaterThan(String value) {
            addCriterion("T_MSG_TITLE >", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleGreaterThanOrEqualTo(String value) {
            addCriterion("T_MSG_TITLE >=", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleLessThan(String value) {
            addCriterion("T_MSG_TITLE <", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleLessThanOrEqualTo(String value) {
            addCriterion("T_MSG_TITLE <=", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleLike(String value) {
            addCriterion("T_MSG_TITLE like", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleNotLike(String value) {
            addCriterion("T_MSG_TITLE not like", value, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleIn(List<String> values) {
            addCriterion("T_MSG_TITLE in", values, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleNotIn(List<String> values) {
            addCriterion("T_MSG_TITLE not in", values, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleBetween(String value1, String value2) {
            addCriterion("T_MSG_TITLE between", value1, value2, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTitleNotBetween(String value1, String value2) {
            addCriterion("T_MSG_TITLE not between", value1, value2, "tMsgTitle");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdIsNull() {
            addCriterion("T_MSG_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdIsNotNull() {
            addCriterion("T_MSG_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdEqualTo(String value) {
            addCriterion("T_MSG_TYPE_ID =", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdNotEqualTo(String value) {
            addCriterion("T_MSG_TYPE_ID <>", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdGreaterThan(String value) {
            addCriterion("T_MSG_TYPE_ID >", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("T_MSG_TYPE_ID >=", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdLessThan(String value) {
            addCriterion("T_MSG_TYPE_ID <", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdLessThanOrEqualTo(String value) {
            addCriterion("T_MSG_TYPE_ID <=", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdLike(String value) {
            addCriterion("T_MSG_TYPE_ID like", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdNotLike(String value) {
            addCriterion("T_MSG_TYPE_ID not like", value, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdIn(List<String> values) {
            addCriterion("T_MSG_TYPE_ID in", values, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdNotIn(List<String> values) {
            addCriterion("T_MSG_TYPE_ID not in", values, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdBetween(String value1, String value2) {
            addCriterion("T_MSG_TYPE_ID between", value1, value2, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTMsgTypeIdNotBetween(String value1, String value2) {
            addCriterion("T_MSG_TYPE_ID not between", value1, value2, "tMsgTypeId");
            return (Criteria) this;
        }

        public Criteria andTContentIsNull() {
            addCriterion("T_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andTContentIsNotNull() {
            addCriterion("T_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andTContentEqualTo(String value) {
            addCriterion("T_CONTENT =", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentNotEqualTo(String value) {
            addCriterion("T_CONTENT <>", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentGreaterThan(String value) {
            addCriterion("T_CONTENT >", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentGreaterThanOrEqualTo(String value) {
            addCriterion("T_CONTENT >=", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentLessThan(String value) {
            addCriterion("T_CONTENT <", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentLessThanOrEqualTo(String value) {
            addCriterion("T_CONTENT <=", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentLike(String value) {
            addCriterion("T_CONTENT like", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentNotLike(String value) {
            addCriterion("T_CONTENT not like", value, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentIn(List<String> values) {
            addCriterion("T_CONTENT in", values, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentNotIn(List<String> values) {
            addCriterion("T_CONTENT not in", values, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentBetween(String value1, String value2) {
            addCriterion("T_CONTENT between", value1, value2, "tContent");
            return (Criteria) this;
        }

        public Criteria andTContentNotBetween(String value1, String value2) {
            addCriterion("T_CONTENT not between", value1, value2, "tContent");
            return (Criteria) this;
        }

        public Criteria andTFileIdIsNull() {
            addCriterion("T_FILE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTFileIdIsNotNull() {
            addCriterion("T_FILE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTFileIdEqualTo(String value) {
            addCriterion("T_FILE_ID =", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdNotEqualTo(String value) {
            addCriterion("T_FILE_ID <>", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdGreaterThan(String value) {
            addCriterion("T_FILE_ID >", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("T_FILE_ID >=", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdLessThan(String value) {
            addCriterion("T_FILE_ID <", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdLessThanOrEqualTo(String value) {
            addCriterion("T_FILE_ID <=", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdLike(String value) {
            addCriterion("T_FILE_ID like", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdNotLike(String value) {
            addCriterion("T_FILE_ID not like", value, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdIn(List<String> values) {
            addCriterion("T_FILE_ID in", values, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdNotIn(List<String> values) {
            addCriterion("T_FILE_ID not in", values, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdBetween(String value1, String value2) {
            addCriterion("T_FILE_ID between", value1, value2, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTFileIdNotBetween(String value1, String value2) {
            addCriterion("T_FILE_ID not between", value1, value2, "tFileId");
            return (Criteria) this;
        }

        public Criteria andTCreateDateIsNull() {
            addCriterion("T_CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTCreateDateIsNotNull() {
            addCriterion("T_CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTCreateDateEqualTo(String value) {
            addCriterion("T_CREATE_DATE =", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateNotEqualTo(String value) {
            addCriterion("T_CREATE_DATE <>", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateGreaterThan(String value) {
            addCriterion("T_CREATE_DATE >", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("T_CREATE_DATE >=", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateLessThan(String value) {
            addCriterion("T_CREATE_DATE <", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateLessThanOrEqualTo(String value) {
            addCriterion("T_CREATE_DATE <=", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateLike(String value) {
            addCriterion("T_CREATE_DATE like", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateNotLike(String value) {
            addCriterion("T_CREATE_DATE not like", value, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateIn(List<String> values) {
            addCriterion("T_CREATE_DATE in", values, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateNotIn(List<String> values) {
            addCriterion("T_CREATE_DATE not in", values, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateBetween(String value1, String value2) {
            addCriterion("T_CREATE_DATE between", value1, value2, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTCreateDateNotBetween(String value1, String value2) {
            addCriterion("T_CREATE_DATE not between", value1, value2, "tCreateDate");
            return (Criteria) this;
        }

        public Criteria andTSendorIsNull() {
            addCriterion("T_SENDOR is null");
            return (Criteria) this;
        }

        public Criteria andTSendorIsNotNull() {
            addCriterion("T_SENDOR is not null");
            return (Criteria) this;
        }

        public Criteria andTSendorEqualTo(String value) {
            addCriterion("T_SENDOR =", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorNotEqualTo(String value) {
            addCriterion("T_SENDOR <>", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorGreaterThan(String value) {
            addCriterion("T_SENDOR >", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorGreaterThanOrEqualTo(String value) {
            addCriterion("T_SENDOR >=", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorLessThan(String value) {
            addCriterion("T_SENDOR <", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorLessThanOrEqualTo(String value) {
            addCriterion("T_SENDOR <=", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorLike(String value) {
            addCriterion("T_SENDOR like", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorNotLike(String value) {
            addCriterion("T_SENDOR not like", value, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorIn(List<String> values) {
            addCriterion("T_SENDOR in", values, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorNotIn(List<String> values) {
            addCriterion("T_SENDOR not in", values, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorBetween(String value1, String value2) {
            addCriterion("T_SENDOR between", value1, value2, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTSendorNotBetween(String value1, String value2) {
            addCriterion("T_SENDOR not between", value1, value2, "tSendor");
            return (Criteria) this;
        }

        public Criteria andTStatusIsNull() {
            addCriterion("T_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andTStatusIsNotNull() {
            addCriterion("T_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andTStatusEqualTo(String value) {
            addCriterion("T_STATUS =", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusNotEqualTo(String value) {
            addCriterion("T_STATUS <>", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusGreaterThan(String value) {
            addCriterion("T_STATUS >", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusGreaterThanOrEqualTo(String value) {
            addCriterion("T_STATUS >=", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusLessThan(String value) {
            addCriterion("T_STATUS <", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusLessThanOrEqualTo(String value) {
            addCriterion("T_STATUS <=", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusLike(String value) {
            addCriterion("T_STATUS like", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusNotLike(String value) {
            addCriterion("T_STATUS not like", value, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusIn(List<String> values) {
            addCriterion("T_STATUS in", values, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusNotIn(List<String> values) {
            addCriterion("T_STATUS not in", values, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusBetween(String value1, String value2) {
            addCriterion("T_STATUS between", value1, value2, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTStatusNotBetween(String value1, String value2) {
            addCriterion("T_STATUS not between", value1, value2, "tStatus");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorIsNull() {
            addCriterion("T_IS_RECEIVOR is null");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorIsNotNull() {
            addCriterion("T_IS_RECEIVOR is not null");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorEqualTo(String value) {
            addCriterion("T_IS_RECEIVOR =", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorNotEqualTo(String value) {
            addCriterion("T_IS_RECEIVOR <>", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorGreaterThan(String value) {
            addCriterion("T_IS_RECEIVOR >", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorGreaterThanOrEqualTo(String value) {
            addCriterion("T_IS_RECEIVOR >=", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorLessThan(String value) {
            addCriterion("T_IS_RECEIVOR <", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorLessThanOrEqualTo(String value) {
            addCriterion("T_IS_RECEIVOR <=", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorLike(String value) {
            addCriterion("T_IS_RECEIVOR like", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorNotLike(String value) {
            addCriterion("T_IS_RECEIVOR not like", value, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorIn(List<String> values) {
            addCriterion("T_IS_RECEIVOR in", values, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorNotIn(List<String> values) {
            addCriterion("T_IS_RECEIVOR not in", values, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorBetween(String value1, String value2) {
            addCriterion("T_IS_RECEIVOR between", value1, value2, "tIsReceivor");
            return (Criteria) this;
        }

        public Criteria andTIsReceivorNotBetween(String value1, String value2) {
            addCriterion("T_IS_RECEIVOR not between", value1, value2, "tIsReceivor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table msg_type
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}