package com.chan.model;

import com.chan.util.BaseModel;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Testbank extends BaseModel {
    public static Integer MSG_TYPE_ID = 10;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.TEST_ID
     *
     * @mbggenerated
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.ANSWER
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.SENDOR
     *
     * @mbggenerated
     */
    private Integer sendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.RIGHTSELECT
     *
     * @mbggenerated
     */
    private String rightselect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.ERRORSELECT_1
     *
     * @mbggenerated
     */
    private String errorselect1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.ERRORSELECT_2
     *
     * @mbggenerated
     */
    private String errorselect2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.ERRORSELECT_3
     *
     * @mbggenerated
     */
    private String errorselect3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testbank.STATUS
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    public Testbank(Integer testId, String title, String answer, Integer sendor, Date createDate, String rightselect, String errorselect1, String errorselect2, String errorselect3, Byte status) {
        this.testId = testId;
        this.title = title;
        this.answer = answer;
        this.sendor = sendor;
        this.createDate = createDate;
        this.rightselect = rightselect;
        this.errorselect1 = errorselect1;
        this.errorselect2 = errorselect2;
        this.errorselect3 = errorselect3;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.TEST_ID
     *
     * @return the value of testbank.TEST_ID
     * @mbggenerated
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.TITLE
     *
     * @return the value of testbank.TITLE
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.ANSWER
     *
     * @return the value of testbank.ANSWER
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.SENDOR
     *
     * @return the value of testbank.SENDOR
     * @mbggenerated
     */
    public Integer getSendor() {
        return sendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.CREATE_DATE
     *
     * @return the value of testbank.CREATE_DATE
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.RIGHTSELECT
     *
     * @return the value of testbank.RIGHTSELECT
     * @mbggenerated
     */
    public String getRightselect() {
        return rightselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.ERRORSELECT_1
     *
     * @return the value of testbank.ERRORSELECT_1
     * @mbggenerated
     */
    public String getErrorselect1() {
        return errorselect1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.ERRORSELECT_2
     *
     * @return the value of testbank.ERRORSELECT_2
     * @mbggenerated
     */
    public String getErrorselect2() {
        return errorselect2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.ERRORSELECT_3
     *
     * @return the value of testbank.ERRORSELECT_3
     * @mbggenerated
     */
    public String getErrorselect3() {
        return errorselect3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testbank.STATUS
     *
     * @return the value of testbank.STATUS
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    public Testbank() {
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public void setSendor(Integer sendor) {
        this.sendor = sendor;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public void setRightselect(String rightselect) {
        this.rightselect = rightselect;
    }

    public void setErrorselect1(String errorselect1) {
        this.errorselect1 = errorselect1;
    }

    public void setErrorselect2(String errorselect2) {
        this.errorselect2 = errorselect2;
    }

    public void setErrorselect3(String errorselect3) {
        this.errorselect3 = errorselect3;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    private String p_sendor;

    public String getP_sendor() {
        return p_sendor;
    }

    public void setP_sendor(String p_sendor) {
        this.p_sendor = p_sendor;
    }

    public String getP_createDate() {
        SimpleDateFormat format = new SimpleDateFormat("YYYY年MM月dd日 HH:mm");
        return format.format(this.createDate);
    }

    private String selected;

    public void setSelected(Object selected) {
        if (selected == null) return;
        this.selected = (String) selected;
    }

    public boolean getIsRight() {
        return rightselect.equals(selected);
    }

    public Integer getP_msgId() {
        return p_msgId;
    }

    public void setP_msgId(Integer p_msgId) {
        this.p_msgId = p_msgId;
    }

    private Integer p_msgId;

}