package com.chan.model;

import com.chan.util.BaseModel;
import org.springframework.stereotype.Component;

@Component
public class TestKnowrelation extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_knowrelation.RELATION_ID
     *
     * @mbggenerated
     */
    private Integer relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_knowrelation.TEST_ID
     *
     * @mbggenerated
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_knowrelation.MSG_ID
     *
     * @mbggenerated
     */
    private Integer msgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    public TestKnowrelation(Integer relationId, Integer testId, Integer msgId) {
        this.relationId = relationId;
        this.testId = testId;
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_knowrelation.RELATION_ID
     *
     * @return the value of test_knowrelation.RELATION_ID
     * @mbggenerated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_knowrelation.TEST_ID
     *
     * @return the value of test_knowrelation.TEST_ID
     * @mbggenerated
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_knowrelation.MSG_ID
     *
     * @return the value of test_knowrelation.MSG_ID
     * @mbggenerated
     */
    public Integer getMsgId() {
        return msgId;
    }

    public TestKnowrelation() {
    }

    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
}