package com.chan.model;

import com.chan.util.BaseModel;
import org.springframework.stereotype.Component;

import java.text.SimpleDateFormat;
import java.util.Date;

@Component
public class Users extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.AGE
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.SEX
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.HEAD_SRC
     *
     * @mbggenerated
     */
    private String headSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PWD_QUESTION
     *
     * @mbggenerated
     */
    private String pwdQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PWD_ANSWER
     *
     * @mbggenerated
     */
    private String pwdAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ROOT
     *
     * @mbggenerated
     */
    private Byte root;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.STATUS
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Users(Integer userId, String name, String address, String email, String phone, String qq, Integer age, Byte sex, String headSrc, String username, String password, String pwdQuestion, String pwdAnswer, Date createDate, Date lastLoginDate, Byte root, Byte status) {
        this.userId = userId;
        this.name = name;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.qq = qq;
        this.age = age;
        this.sex = sex;
        this.headSrc = headSrc;
        this.username = username;
        this.password = password;
        this.pwdQuestion = pwdQuestion;
        this.pwdAnswer = pwdAnswer;
        this.createDate = createDate;
        this.lastLoginDate = lastLoginDate;
        this.root = root;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_ID
     *
     * @return the value of users.USER_ID
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.NAME
     *
     * @return the value of users.NAME
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ADDRESS
     *
     * @return the value of users.ADDRESS
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.EMAIL
     *
     * @return the value of users.EMAIL
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PHONE
     *
     * @return the value of users.PHONE
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.QQ
     *
     * @return the value of users.QQ
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.AGE
     *
     * @return the value of users.AGE
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.SEX
     *
     * @return the value of users.SEX
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.HEAD_SRC
     *
     * @return the value of users.HEAD_SRC
     * @mbggenerated
     */
    public String getHeadSrc() {
        return headSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USERNAME
     *
     * @return the value of users.USERNAME
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PASSWORD
     *
     * @return the value of users.PASSWORD
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PWD_QUESTION
     *
     * @return the value of users.PWD_QUESTION
     * @mbggenerated
     */
    public String getPwdQuestion() {
        return pwdQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PWD_ANSWER
     *
     * @return the value of users.PWD_ANSWER
     * @mbggenerated
     */
    public String getPwdAnswer() {
        return pwdAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CREATE_DATE
     *
     * @return the value of users.CREATE_DATE
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.LAST_LOGIN_DATE
     *
     * @return the value of users.LAST_LOGIN_DATE
     * @mbggenerated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ROOT
     *
     * @return the value of users.ROOT
     * @mbggenerated
     */
    public Byte getRoot() {
        return root;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.STATUS
     *
     * @return the value of users.STATUS
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public void setHeadSrc(String headSrc) {
        this.headSrc = headSrc;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setPwdQuestion(String pwdQuestion) {
        this.pwdQuestion = pwdQuestion;
    }

    public void setPwdAnswer(String pwdAnswer) {
        this.pwdAnswer = pwdAnswer;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public void setRoot(Byte root) {
        this.root = root;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Users() {
    }

    public String getP_lastLoginDate() {
        SimpleDateFormat format = new SimpleDateFormat("YYYY年MM月dd日 HH:mm");
        return format.format(this.lastLoginDate);
    }
}