package com.chan.dao;

import com.chan.model.MsgFile;
import com.chan.model.MsgFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MsgFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int countByExample(MsgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int deleteByExample(MsgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int insert(MsgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int insertSelective(MsgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    List<MsgFile> selectByExample(MsgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    MsgFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MsgFile record, @Param("example") MsgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MsgFile record, @Param("example") MsgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgFile record);
}