package com.chan.dao;

import com.chan.model.MsgRelation;
import com.chan.model.MsgRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MsgRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int countByExample(MsgRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int deleteByExample(MsgRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int insert(MsgRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int insertSelective(MsgRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    List<MsgRelation> selectByExample(MsgRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    MsgRelation selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MsgRelation record, @Param("example") MsgRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MsgRelation record, @Param("example") MsgRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MsgRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MsgRelation record);
}