package com.chan.dao;

import com.chan.model.TestKnowrelation;
import com.chan.model.TestKnowrelationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TestKnowrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int countByExample(TestKnowrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int deleteByExample(TestKnowrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int insert(TestKnowrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int insertSelective(TestKnowrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    List<TestKnowrelation> selectByExample(TestKnowrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    TestKnowrelation selectByPrimaryKey(Integer relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TestKnowrelation record, @Param("example") TestKnowrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TestKnowrelation record, @Param("example") TestKnowrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestKnowrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_knowrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestKnowrelation record);
}