package com.chan.dao;

import com.chan.model.Testbank;
import com.chan.model.TestbankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TestbankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int countByExample(TestbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int deleteByExample(TestbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int insert(Testbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int insertSelective(Testbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    List<Testbank> selectByExample(TestbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    Testbank selectByPrimaryKey(Integer testId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Testbank record, @Param("example") TestbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Testbank record, @Param("example") TestbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Testbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Testbank record);
}